# Generated by Django 6.0.6 on 2026-06-10 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('education', 'Education'), ('politics', 'Politics'), ('technology', 'Technology')], max_length=50)),
                ('state', models.CharField(choices=[('andhra', 'Andhra Pradesh'), ('tamilnadu', 'Tamil Nadu'), ('telangana', 'Telangana')], max_length=50)),
                ('is_fake', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
